### ISSUE TITLE
MVRT Resources

### ISSUE THREAD

**Issue by akhil99** [mvrt-115/MVRT_Site#142]
1. Team resources should come first, before things like TBA and CD
2. We need to add our FIRST Aid Kit
3. We need to add all of the resources currently on our main site, like awards submissions and other documentation
4. Do we have something from beta last year?
5. Missing things like scholarship info

**Comment by akalari** [comment]
Awards submissions not necessary. Maybe start fresh this year.
Scholarship info will be added. FIRST aid kid will be added a s well.
