### ISSUE TITLE
Misc. Missing Info

### ISSUE THREAD

**Issue by akhil99** [mvrt-115/MVRT_Site#144]
1. Outreach information (specifics about each program)
2. Alumni stories
3. Newsletters (maybe an archive?)
4. Resources -> Sensor link currently points to an invalid link
5. Missing more information about each division, iirc we had more than just a short blurb

**Comment by akalari** [comment]
Alumni stories will not be added.
Resources should be fixed soon.
We never had info on divisions until now.
Newsletters are for mail only.
Outreach Being Collected By @arushirai1
