### ISSUE TITLE
Header Overflow

### ISSUE THREAD

**Issue by m3rcuriel** [mvrt-115/MVRT_Site#51]
The header overflows, and needs to be fixed.

Perhaps `overflow: hidden` is a temporary fix.

**Comment by trotod** [comment]
if this is only for smaller screens (which has been a problem for a while), then i'll try hacking a media query to fix this

**Comment by m3rcuriel** [comment]
Um. It occurs on window resize as well.

**Comment by trotod** [comment]
Not sure what exactly is happening. Nothing overflows on my part, as far as my definition goes (no weird scrollbars, essentially)

if this is a [problem with the header covering the sponsors stuff](http://a.pomf.se/gcrede.png), maybe the header shouldn't be `position: fixed`

But again, not sure what the problem exactly is.

**Comment by m3rcuriel** [comment]
http://puu.sh/eJ3yx/1fc8c4a81d.jpg

**Comment by trotod** [comment]
thought i fixed that in #52

**Comment by m3rcuriel** [comment]
Haven't pulled that yet.

**Comment by trotod** [comment]
fixed in #91
