### ISSUE TITLE
members (only?) pages

### ISSUE THREAD

**Issue by trotod** [mvrt-115/MVRT_Site#95]
should this be

- a separate project
- scrapped in favor of emails + google groups
- or public and static pages on the website?

**Comment by shovikguha** [comment]
As of now I don't see a need for it as we got along just fine this build season without it. I think we should put it to the side for now.

**Comment by m3rcuriel** [comment]
@trotod First things first we need to stabilize the existing system, and then this needs to be discussed with the whole officer team.
